
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: community_management_system_development

test:
  <<: *default
  database: community_management_system_test

production:
  <<: *default
  database: community_management_system_production
  username: community_management_system
  password: <%= ENV['COMMUNITY_MANAGEMENT_SYSTEM_DATABASE_PASSWORD'] %>
